##########################################
#1、应用基础配置
#   描述:引用pom.xml时，必须在application.yml加载顺序之后。bootstrap.yml就不能获取到pom.xml的属性
#
#   @@ 内标记的变量，均由maven编译时动态的从pom.xml 替换到yml中
#
##########################################
spring:
  application:
    name: @pom.groupId@.@pom.artifactId@
  netty:
    web:
      custom:
        accept-group-pool-name: 1
        worker-group-thread: 2
  profiles:
    active: @spring.cloud.config.profile@

eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
server:
  port: 9001


logging:
  config: classpath:log4j2.xml



